# copyright Utrecht University
# Always redirect plain HTTP to HTTPS for every hostnanme.
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    location / {
        return 301 https://$host$request_uri;
    }
}
