---
# copyright Utrecht University

paleo_user: paleo

# Site identity.
paleo_host_name: www.paleo.test

# First-run WordPress install values
paleo_first_site_title: "Paleo Earth Demo - WordPress site"
paleo_first_user_name: admin
paleo_first_user_email: paleo-example@uu.nl
# DEV-ONLY DEFAULT
paleo_first_user_password: paleopassword

# DEV-ONLY defaults.
paleo_mariadb_password: devpassword
paleo_mariadb_root_password: devrootpassword
